#
#   TU Eindhoven
#   Eindhoven, The Netherlands
#
#   Author          :   Sander Stuijk (sander@ics.ele.tue.nl)
#
#   Date            :   March 29, 2002
#   
#   $Id: Makefile,v 1.2 2008/02/29 15:24:49 sander Exp $

include $(PRIVATE_CM_ROOT)/sdf3/etc/Makefile.inc

#-------------------------------------------------------------------------------
# Variables
#-------------------------------------------------------------------------------

COMPONENTS      = binding_aware_sdfg flow mpsoc_arch noc_allocation scheduling \
                  tile_allocation
MODULE_SH_LIB   = 
TOOLS           = 

#-------------------------------------------------------------------------------
# Rules
#-------------------------------------------------------------------------------

include $(PRIVATE_CM_ROOT)/sdf3/etc/Makefile-modules.rules

#-------------------------------------------------------------------------------
# Additional rules
#-------------------------------------------------------------------------------
