#
#   TU Eindhoven
#   Eindhoven, The Netherlands
#
#   Author          :   Bart Theelen (B.D.Theelen@tue.nl)
#
#   Date            :   26 August 2006

include $(PRIVATE_CM_ROOT)/sdf3/etc/Makefile.inc

#-------------------------------------------------------------------------------
# Variables
#-------------------------------------------------------------------------------

COMPONENTS      =
MODULE_SH_LIB   = 
TOOLS           = sdf3verify sdf3analyze sdf3transform sdf3convert sdf3print #sdf3simulate

#-------------------------------------------------------------------------------
# Rules
#-------------------------------------------------------------------------------

include $(PRIVATE_CM_ROOT)/sdf3/etc/Makefile-modules.rules

#-------------------------------------------------------------------------------
# Additional rules
#-------------------------------------------------------------------------------
