#
#   TU Eindhoven
#   Eindhoven, The Netherlands
#
#   Author          :   Bart Theelen (B.D.Theelen@tue.nl)
#
#   Date            :   29 August 2006

include $(PRIVATE_CM_ROOT)/sdf3/etc/Makefile.inc

#-------------------------------------------------------------------------------
# Variables
#-------------------------------------------------------------------------------

# Source files that need to be handled (e.g. foo.cc)
SRCS = $(wildcard *.cc)


# Name of the static library (e.g. libfoo.a)
PROG_LIB = $(LIB)$(MODULE).$(LIBA)

# Name of include files needed in distribution (e.g. foo.h)
PROG_INC = 

# Name of the binary in distribution (e.g. foo)
PROG_BIN =

#-------------------------------------------------------------------------------
# Rules
#-------------------------------------------------------------------------------

include $(PRIVATE_CM_ROOT)/sdf3/etc/Makefile.rules

#-------------------------------------------------------------------------------
# Additional rules
#-------------------------------------------------------------------------------
