#
#   TU Eindhoven
#   Eindhoven, The Netherlands
#
#   Author          :   Sander Stuijk (sander@ics.ele.tue.nl)
#
#   Date            :   March 29, 2002
#   
#   $Id: Makefile,v 1.2 2008/03/04 10:28:41 btheelen Exp $

include $(PRIVATE_CM_ROOT)/sdf3/etc/Makefile.inc

#-------------------------------------------------------------------------------
# Variables
#-------------------------------------------------------------------------------

COMPONENTS      = exception fraction log math matrix sort string tempfile xml
TOOLS           = 
MODULE_SH_LIB   = $(LIB)$(MODULE).$(LIBSO)

#-------------------------------------------------------------------------------
# Rules
#-------------------------------------------------------------------------------

include $(PRIVATE_CM_ROOT)/sdf3/etc/Makefile-modules.rules

#-------------------------------------------------------------------------------
# Additional rules
#-------------------------------------------------------------------------------
